### ISSUE TITLE
fakesu: command not found

### ISSUE THREAD

**Issue by bnsave100** [XenonTheInertG/Sudo-Mask#1]
~ $ fakesu
bash: fakesu: command not found

what to do

**Comment by XenonTheInertG** [comment]
Add this buildpack manually

**Comment by Dhananjay-JSR** [comment]
same issue

**Comment by Dhananjay-JSR** [comment]
> 
> 
> > Add this buildpack manually
> 
> manually means ?

he means deploying Buildpack manually by using the dashboard but still it didn't work

**Comment by bnsave100** [comment]
> 
> he means deploying Buildpack manually by using the dashboard but still it didn't work

I just saw u have updated the repo, it worked for you ???
