### ISSUE TITLE
Push rejected, failed to compile fakesu app.

### ISSUE THREAD

**Issue by marat2509** [XenonTheInertG/Sudo-Mask#15]
remote: -----> fakesu app detected                            remote: -----> Fetching and Installing wget                   remote:  !     Push rejected, failed to compile fakesu app.   remote:                                                       remote:  !     Push failed                                    remote:  !                                                    remote:  ! ## Warning - The same version of this code has already been built: c196be84e2fad209462d5113ab3b03bceb781c53      remote:  !                                                    remote:  ! We have detected that you have triggered a build from source code with version c196be84e2fad209462d5113ab3b03bceb781c53                                                        remote:  ! at least twice. One common cause of this behavior is attempting to deploy code from a different branch.          remote:  !                                                    remote:  ! If you are developing on a branch and deploying via git you must run:                                            remote:  !                                                    remote:  !     git push heroku <branchname>:main              remote:  !                                                    remote:  ! This article goes into details on the behavior:    remote:  !   https://devcenter.heroku.com/articles/duplicate-build-version

**Comment by XenonTheInertG** [comment]
Did you push it to a existing app or a blank app?
First deploy your app & add this in buildpack later

**Comment by marat2509-hub** [comment]
I tried it at once in the existing one - it did not help. Likewise with the new

**Comment by Syzygianinfern0** [comment]
@XenonTheInertG could you please share CLI commands using which you can deploy it on a blank app? There should be something I am missing :(
